version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@babel/runtime"
    versions:
    - 7.13.10
    - 7.13.9
  - dependency-name: "@types/react"
    versions:
    - 17.0.2
    - 17.0.3
  - dependency-name: puppeteer
    versions:
    - 8.0.0
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.0
  - dependency-name: nzh
    versions:
    - 1.0.4
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: handlebars
    versions:
    - 4.7.6
